let detallesDiagnostico=[];
function mostrarListarDiagnostico(){let c=dameContenido("paginas/referenciales/diagnostico/listar.php");$("#contenido-principal").html(c);cargarTablaDiagnostico();}
window.mostrarListarDiagnostico=mostrarListarDiagnostico;
function mostrarAgregarDiagnostico(){let c=dameContenido("paginas/referenciales/diagnostico/agregar.php");$("#contenido-principal").html(c);detallesDiagnostico=[];cargarListaRecepciones();}
window.mostrarAgregarDiagnostico=mostrarAgregarDiagnostico;
function cargarListaRecepciones(selId=""){let d=ejecutarAjax("controladores/recepcion.php","leer=1"),$s=$("#id_recepcion_lst");$s.html('<option value="">-- Seleccione --</option>');if(d!=="0"){JSON.parse(d).forEach(r=>$s.append(`<option value="${r.id_recepcion}">${r.id_recepcion} - ${r.nombre_cliente}</option>`));if(selId)$s.val(selId);}}
$(document).on("change","#id_recepcion_lst",function(){let id=$(this).val(),$s=$("#id_detalle_lst");$s.html('<option value="">-- Equipo --</option>');if(id){let det=ejecutarAjax("controladores/detalle_recepcion.php","leer=1&id_recepcion="+id);if(det!=="0")JSON.parse(det).forEach(d=>$s.append(`<option value="${d.id_detalle}">${d.nombre_equipo}</option>`));}});
function agregarDetalleDiagnostico(){if($("#componente_txt").val().trim()===''){mensaje_dialogo_info_ERROR("Ingrese componente","ERROR");return;}let det={componente:$("#componente_txt").val().trim(),estado_componente:$("#estado_comp_lst").val(),hallazgo:$("#hallazgo_txt").val().trim(),accion_recomendada:$("#accion_txt").val().trim(),id_repuesto:null,cantidad_repuesto:0,costo_unitario_estimado:0,costo_linea_estimado:0,nota_adicional:null};detallesDiagnostico.push(det);renderDetallesDiagnostico();$("#componente_txt,#hallazgo_txt,#accion_txt").val('');}
window.agregarDetalleDiagnostico=agregarDetalleDiagnostico;
function renderDetallesDiagnostico(){let tb=$("#detalle_diagnostico_tb");tb.html('');detallesDiagnostico.forEach((d,i)=>tb.append(`<tr><td>${d.componente}</td><td>${d.estado_componente}</td><td>${d.hallazgo}</td><td>${d.accion_recomendada}</td><td><button class="btn btn-danger btn-sm" onclick="eliminarDetalleDiagnostico(${i});return false;"><i class="bi bi-trash"></i></button></td></tr>`));}
function eliminarDetalleDiagnostico(i){detallesDiagnostico.splice(i,1);renderDetallesDiagnostico();}
window.eliminarDetalleDiagnostico=eliminarDetalleDiagnostico;
function guardarDiagnostico(){if($("#id_recepcion_lst").val()===''){mensaje_dialogo_info_ERROR("Seleccione recepción","ERROR");return;}if(detallesDiagnostico.length===0){mensaje_dialogo_info_ERROR("Debe agregar detalle","ERROR");return;}let datos={id_recepcion:$("#id_recepcion_lst").val(),id_detalle_recepcion:$("#id_detalle_lst").val()||null,estado:$("#estado_lst").val(),descripcion_falla:$("#descripcion_falla_txt").val().trim(),tiempo_estimado_horas:parseFloat($("#tiempo_txt").val()||0),costo_mano_obra_estimado:parseFloat($("#costo_mano_txt").val()||0),costo_repuestos_estimado:parseFloat($("#costo_repuestos_txt").val()||0),aplica_garantia:$("#aplica_garantia_lst").val(),observaciones:$("#observaciones_txt").val().trim(),creado_por:1};datos.costo_total_estimado=datos.costo_mano_obra_estimado+datos.costo_repuestos_estimado;let id=$("#id_diagnostico").val();if(id==="0"){id=ejecutarAjax("controladores/diagnostico.php","guardar="+JSON.stringify(datos));detallesDiagnostico.forEach(d=>{d={...d,id_diagnostico:id};ejecutarAjax("controladores/detalle_diagnostico.php","guardar="+JSON.stringify(d));});}else{datos={...datos,id_diagnostico:id,modificado_por:1};ejecutarAjax("controladores/diagnostico.php","actualizar="+JSON.stringify(datos));ejecutarAjax("controladores/detalle_diagnostico.php","eliminar_por_diagnostico="+id);detallesDiagnostico.forEach(d=>{d={...d,id_diagnostico:id};ejecutarAjax("controladores/detalle_diagnostico.php","guardar="+JSON.stringify(d));});}mensaje_confirmacion("Guardado correctamente");mostrarListarDiagnostico();}
window.guardarDiagnostico=guardarDiagnostico;
function imprimirDiagnostico(id){let d=ejecutarAjax("controladores/diagnostico.php","leer_id="+id);if(d==="0"){alert("No se encontró el diagnóstico");return;}let diag=JSON.parse(d);let det=ejecutarAjax("controladores/detalle_diagnostico.php","leer=1&id_diagnostico="+id),filas="";if(det!=="0"){JSON.parse(det).forEach(e=>{filas+=`<tr><td>${e.componente}</td><td>${e.estado_componente}</td><td>${e.hallazgo}</td><td>${e.accion_recomendada}</td></tr>`;});}let v=window.open('', '', 'width=900,height=700');v.document.write(`<html><head><title>Diagnóstico #${diag.id_diagnostico}</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body style="padding:30px;font-size:14px;"><h3 class="mb-4">Diagnóstico #${diag.id_diagnostico}</h3><p><strong>Recepción:</strong> ${diag.id_recepcion}</p><p><strong>Estado:</strong> ${diag.estado}</p><p><strong>Descripción de falla:</strong> ${diag.descripcion_falla||''}</p><p><strong>Observaciones:</strong> ${diag.observaciones||''}</p><table class="table table-bordered"><thead><tr><th>Componente</th><th>Estado</th><th>Hallazgo</th><th>Acción</th></tr></thead><tbody>${filas}</tbody></table></body></html>`);v.document.close();v.focus();v.print();}
window.imprimirDiagnostico=imprimirDiagnostico;
function cargarTablaDiagnostico(){let datos=ejecutarAjax("controladores/diagnostico.php","leer=1");if(datos==="0"){$("#diagnostico_datos_tb").html("NO HAY REGISTROS");}else{let js=JSON.parse(datos);$("#diagnostico_datos_tb").html('');js.forEach(it=>{$("#diagnostico_datos_tb").append(`<tr><td>${it.id_diagnostico}</td><td>${it.id_recepcion} - ${it.nombre_cliente}</td><td>${it.fecha_inicio}</td><td>${badgeEstado(it.estado)}</td><td><button class="btn btn-secondary btn-sm imprimir-diagnostico" data-id="${it.id_diagnostico}"><i class="bi bi-printer"></i></button> <button class="btn btn-warning btn-sm editar-diagnostico" data-id="${it.id_diagnostico}"><i class="bi bi-pencil-square"></i></button> <button class="btn btn-danger btn-sm eliminar-diagnostico" data-id="${it.id_diagnostico}"><i class="bi bi-trash"></i></button></td></tr>`);});}}
function cargarDiagnostico(id){let d=ejecutarAjax("controladores/diagnostico.php","leer_id="+id);if(d!=='0'){let j=JSON.parse(d);mostrarAgregarDiagnostico();$("#id_diagnostico").val(j.id_diagnostico);$("#estado_lst").val(j.estado);$("#descripcion_falla_txt").val(j.descripcion_falla);$("#observaciones_txt").val(j.observaciones);$("#tiempo_txt").val(j.tiempo_estimado_horas);$("#costo_mano_txt").val(j.costo_mano_obra_estimado);$("#costo_repuestos_txt").val(j.costo_repuestos_estimado);$("#aplica_garantia_lst").val(j.aplica_garantia);cargarListaRecepciones(j.id_recepcion);let detRec=ejecutarAjax("controladores/detalle_recepcion.php","leer=1&id_recepcion="+j.id_recepcion);if(detRec!=='0'){let arr=JSON.parse(detRec),$s=$("#id_detalle_lst");arr.forEach(e=>$s.append(`<option value="${e.id_detalle}">${e.nombre_equipo}</option>`));$s.val(j.id_detalle_recepcion);}let det=ejecutarAjax("controladores/detalle_diagnostico.php","leer=1&id_diagnostico="+id);if(det!=='0'){detallesDiagnostico=JSON.parse(det);renderDetallesDiagnostico();}}}
$(document).on("click",".editar-diagnostico",function(){cargarDiagnostico($(this).data('id'));});
$(document).on("click",".eliminar-diagnostico",function(){if(confirm("¿Eliminar?")){ejecutarAjax("controladores/diagnostico.php","eliminar="+$(this).data('id'));cargarTablaDiagnostico();}});
$(document).on("click",".imprimir-diagnostico",function(){imprimirDiagnostico($(this).data('id'));});
